import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const rilenoSans = localFont({
  src: [
    {
      path: 'assets/rileno-sans/RilenoSans-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: 'assets/rileno-sans/RilenoSans-Light.woff',
      weight: '400',
      style: 'bold',
    },
    {
      path: 'assets/rileno-sans/RilenoSans-SemiBold.woff',
      weight: '600',
      style: 'bold',
    },
  ]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rilenoSans.className} "bg-white"`}>{children}</body>
    </html>
  );
}
