import { Metadata } from "next";
import Head from "next/head";

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//     viewport: 'width=device-width, initial-scale=1, maximum-scale=1', // <-- here
//   }

function ImageShare() {
    return (
        <>
            <main>
                <h1>Hello world</h1>
            </main>
        </>
    )
}
export default ImageShare;